spring:
  datasource:
    url: jdbc:mysql://localhost:3306/udeedb?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
      driverClassName: com.mysql.cj.jdbc.Driver
    database: mysql